# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

concat_vectors <- function(list1, list2) {
    .Call('_Skilift_concat_vectors', PACKAGE = 'Skilift', list1, list2)
}

